name: Discord Notifications
description: Sends Discord Notifications, using a webhook.
inputs:
  webhook_id:
    description: Discord's webhook id.
    required: false
  webhook_token:
    description: Discord's webhook token.
    required: false
  webhook_id_token:
    description: Discord's webhook id and Discord's webhook token "id/token".
    required: false
  title:
    description: Title of the message
    required: false
    default: Release VERSION
  color:
    description: Embed Color
    required: false
    default: "3447003"
  description:
    description: Embeded Message Contents
    required: false
  url:
    description: Title URL
    required: false
  username:
    description: Message Username
    required: false
  avatar_url:
    description: Avatar URL
    required: false
  author:
    description: Author Name
    required: false
  author_url:
    description: Author Name URL
    required: false
  author_icon_url:
    description: Author Icon URL
    required: false
  message:
    description: Message Contents
    required: false
  release:
    description: Add Github Release to Description
    required: false
    default: "false"
  commits:
    description: Add Github Commits to Description
    required: false
    default: "false"
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: orange
  icon: align-justify